sudo: required

services:
 - docker

before_install:
  - docker build -t ofir/react_test_fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ofir/react_test_fib npm test -- --coverage

after_success:
  - docker build -t ofiredi585/multi-client ./client
  - docker build -t ofiredi585/multi-server ./server
  - docker build -t ofiredi585/multi-nginx ./nginx
  - docker build -t ofiredi585/multi-worker ./worker
  #log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to dockerhub
  - docker push ofiredi585/multi-client
  - docker push ofiredi585/multi-server
  - docker push ofiredi585/multi-nginx 
  - docker push ofiredi585/multi-worker

deploy:
  deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react_prod"
  env: "multiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-369106132999"
  bucket_path: "react_prod"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
